[/]
prompt-on-close=true
quake-alignment='center'
quake-height-percent=12
quake-specific-monitor=0
quake-window-position='top'
terminal-title-style='none'
unsafe-paste-alert=false
window-style='disable-csd-hide-toolbar'

[keybindings]
app-preferences='<Primary>p'
session-add-down='<Primary>F5'
session-add-right='<Primary>F6'
session-resize-terminal-down='<Primary><Shift>Down'
session-resize-terminal-left='<Primary><Shift>Left'
session-resize-terminal-right='<Primary><Shift>Right'
session-resize-terminal-up='<Primary><Shift>Up'
session-switch-to-terminal-left='disabled'
session-switch-to-terminal-right='disabled'
terminal-close='<Primary>n'
terminal-scroll-down='disabled'
terminal-scroll-up='disabled'
win-switch-to-next-session='<Alt>Right'
win-switch-to-previous-session='<Alt>Left'

[profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d]
background-color='#0A0A0A0A0A0A'
background-transparency-percent=0
badge-color='#AC7EA8'
badge-color-set=false
badge-font='JetBrains Mono Medium 9'
badge-position='southwest'
badge-text=''
badge-use-system-font=true
bold-color-set=false
bold-is-bright=false
cursor-background-color='#A2A2FFFFEBEB'
cursor-blink-mode='off'
cursor-colors-set=false
cursor-shape='ibeam'
default-size-columns=140
default-size-rows=40
dim-transparency-percent=0
draw-margin=80
font='JetBrains Mono Medium 10'
foreground-color='#4A4A4A4A4F4F'
highlight-background-color='#0A0A0A0A0A0A'
highlight-colors-set=true
highlight-foreground-color='#9F9FEFEF0000'
palette=['#4A4A4A4A4F4F', '#E2E277777777', '#C0C0CACA8E8E', '#E9E9B1B18989', '#9191ACACD1D1', '#ADADA0A0D3D3', '#9595C4C4CECE', '#777776767B7B', '#4A4A4A4A4F4F', '#E2E277777777', '#C0C0CACA8E8E', '#E9E9B1B18989', '#9191ACACD1D1', '#ADADA0A0D3D3', '#9595C4C4CECE', '#777776767B7B']
show-scrollbar=false
terminal-bell='none'
terminal-title='${id}: ${title} ${rows}-${columns}'
text-blink-mode='never'
use-system-font=false
use-theme-colors=false
visible-name='VIshok'
