# Fonts
font_family JetBrains Mono Medium
font_size 10
cursor_shape beam

# Shortcuts
map ctrl+shift+t new_tab
map ctrl+- close_tab
map alt+left previous_tab
map alt+right next_tab

# Clipboards
map f1 copy_to_buffer a
map f2 paste_from_buffer a
map f3 copy_to_buffer b
map f4 paste_from_buffer b
map f5 copy_to_buffer c
map f6 paste_from_buffer c
map f7 copy_to_buffer d
map f8 paste_from_buffer d

# Tabs
tab_bar_edge bottom
window_margin_width 5
tab_bar_style powerline
active_tab_background #7D7D7D
active_tab_foreground #090909
inactive_tab_background #2A2A2A
inactive_tab_foreground #7D7D7D
inactive_tab_font_style Bold
tab_bar_background #090909

# Selections
selection_foreground #B0B0B0
selection_background #090909

# Colors
foreground #4A4A4F
background #0a0a0a

# Black
color0 #505354
color8 #505354

# Red
color1 #f97583
color9 #f97583

# Green
color2 #b392f0
color10 #b392f0

# Yellow
color3 #ff9966
color11 #ff9966

# Blue
color4 #737174
color12 #737174

# Magenta
color5 #b392f0
color13 #b392f0

# Cyan
color6 #a2ffeb
color14 #a2ffeb

# White
color7 #e4e4e4
color15 #e4e4e4

cursor #4A4A4F
cursor_text_color #4A4A4F

background_opacity 1
shell zsh

# Windows borders
draw_minimal_borders no
placement_strategy center
active_border_color #090909
inactive_border_color #090909

# Split terminal panels
map ctrl+f5 launch --location=vsplit
map ctrl+f6 launch --location=hsplit

# Resize windows
map ctrl+shift+up resize_window taller 5
map ctrl+shift+down resize_window shorter 5
map ctrl+shift+left resize_window wider 5
map ctrl+shift+right resize_window narrower 5

# Tab rename
map ctrl+shift+r set_tab_title
