# Statusbar
set -g status-style bg=default
set -g status-position bottom

# Left columns
set -g status-left '#[fg=#FF6F82][#S] [C-b, 0-9: Switch window] '

# Windows created
set -g window-status-format '#[fg=#4A4A4F]#I:#W'
set -g window-status-current-format '#[fg=#FF9E64]#I:#W'

# Right column
set -g status-right '#[fg=#a2ffeb][#H] [C-b, c: New window]'